default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: <%= ENV['PG_HOST'] %>
  port: <%= ENV['PG_PORT'] %>

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: todo_list_production
  username: todo_list
  password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
