# This is a basic workflow to help you get started with Actions

name: Rubocop Linters
on: [push,pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - name: Install Rubocop
        run: bundle install && gem install rubocop
      - name: Check code
        run: bundle exec rubocop
